all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/mongo.pem
    ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

mongodb:
  hosts:
    mongo:
      # Prefer private IP for intra-VPC SSH
      ansible_host: "{{ lookup('env','MONGODB_PRIVATE_IP') | default(mongodb_private_ip, true) }}"
